from __future__ import annotations

from collections.abc import Iterable

ROLE_CODES = (
    "superuser",
    "administrator",
    "editor",
    "reviewer",
    "viewer",
)

ROLE_PRIORITY = {
    "superuser": 0,
    "administrator": 1,
    "reviewer": 2,
    "editor": 3,
    "viewer": 4,
}

PERMISSION_DEFINITIONS = [
    {"code": "dashboard.read", "module": "dashboard", "action": "read", "description": "View the admin dashboard."},
    {"code": "page.read", "module": "page", "action": "read", "description": "View page records in admin."},
    {"code": "page.create", "module": "page", "action": "create", "description": "Create page drafts."},
    {"code": "page.edit_own_draft", "module": "page", "action": "edit_own_draft", "description": "Edit own page drafts."},
    {"code": "page.edit_any_draft", "module": "page", "action": "edit_any_draft", "description": "Edit any page draft."},
    {"code": "page.submit_review", "module": "page", "action": "submit_review", "description": "Submit pages for review."},
    {"code": "page.approve", "module": "page", "action": "approve", "description": "Approve page submissions."},
    {"code": "page.reject", "module": "page", "action": "reject", "description": "Reject page submissions."},
    {"code": "page.publish", "module": "page", "action": "publish", "description": "Publish pages directly when allowed."},
    {"code": "page.archive", "module": "page", "action": "archive", "description": "Archive pages."},
    {"code": "page.delete", "module": "page", "action": "delete", "description": "Delete pages."},
    {"code": "blog_post.read", "module": "blog_post", "action": "read", "description": "View blog post records in admin."},
    {"code": "blog_post.create", "module": "blog_post", "action": "create", "description": "Create blog post drafts."},
    {"code": "blog_post.edit_own_draft", "module": "blog_post", "action": "edit_own_draft", "description": "Edit own blog post drafts."},
    {"code": "blog_post.edit_any_draft", "module": "blog_post", "action": "edit_any_draft", "description": "Edit any blog post draft."},
    {"code": "blog_post.submit_review", "module": "blog_post", "action": "submit_review", "description": "Submit blog posts for review."},
    {"code": "blog_post.approve", "module": "blog_post", "action": "approve", "description": "Approve blog posts."},
    {"code": "blog_post.reject", "module": "blog_post", "action": "reject", "description": "Reject blog posts."},
    {"code": "blog_post.publish", "module": "blog_post", "action": "publish", "description": "Publish blog posts directly when allowed."},
    {"code": "blog_post.archive", "module": "blog_post", "action": "archive", "description": "Archive blog posts."},
    {"code": "blog_post.delete", "module": "blog_post", "action": "delete", "description": "Delete blog posts."},
    {"code": "blog_category.read", "module": "blog_category", "action": "read", "description": "View blog categories."},
    {"code": "blog_category.manage", "module": "blog_category", "action": "manage", "description": "Create, update, and delete blog categories."},
    {"code": "blog_author.read", "module": "blog_author", "action": "read", "description": "View blog authors."},
    {"code": "blog_author.manage", "module": "blog_author", "action": "manage", "description": "Create, update, and delete blog authors."},
    {"code": "testimonial.read", "module": "testimonial", "action": "read", "description": "View testimonial records in admin."},
    {"code": "testimonial.create", "module": "testimonial", "action": "create", "description": "Create testimonial drafts."},
    {"code": "testimonial.edit_own_draft", "module": "testimonial", "action": "edit_own_draft", "description": "Edit own testimonial drafts."},
    {"code": "testimonial.edit_any_draft", "module": "testimonial", "action": "edit_any_draft", "description": "Edit any testimonial draft."},
    {"code": "testimonial.submit_review", "module": "testimonial", "action": "submit_review", "description": "Submit testimonials for review."},
    {"code": "testimonial.approve", "module": "testimonial", "action": "approve", "description": "Approve testimonials."},
    {"code": "testimonial.reject", "module": "testimonial", "action": "reject", "description": "Reject testimonials."},
    {"code": "testimonial.publish", "module": "testimonial", "action": "publish", "description": "Publish testimonials directly when allowed."},
    {"code": "testimonial.archive", "module": "testimonial", "action": "archive", "description": "Archive testimonials."},
    {"code": "testimonial.delete", "module": "testimonial", "action": "delete", "description": "Delete testimonials."},
    {"code": "media.read", "module": "media", "action": "read", "description": "View media records."},
    {"code": "media.create", "module": "media", "action": "create", "description": "Upload or create media."},
    {"code": "media.update", "module": "media", "action": "update", "description": "Update media metadata."},
    {"code": "media.delete", "module": "media", "action": "delete", "description": "Delete media."},
    {"code": "navigation.read", "module": "navigation", "action": "read", "description": "View navigation items."},
    {"code": "navigation.create", "module": "navigation", "action": "create", "description": "Create navigation items."},
    {"code": "navigation.update", "module": "navigation", "action": "update", "description": "Update navigation items."},
    {"code": "navigation.delete", "module": "navigation", "action": "delete", "description": "Delete navigation items."},
    {"code": "pricing.read", "module": "pricing", "action": "read", "description": "View pricing plans."},
    {"code": "pricing.create", "module": "pricing", "action": "create", "description": "Create pricing plans."},
    {"code": "pricing.update", "module": "pricing", "action": "update", "description": "Update pricing plans."},
    {"code": "pricing.delete", "module": "pricing", "action": "delete", "description": "Delete pricing plans."},
    {"code": "job.read", "module": "job", "action": "read", "description": "View jobs."},
    {"code": "job.create", "module": "job", "action": "create", "description": "Create jobs."},
    {"code": "job.update", "module": "job", "action": "update", "description": "Update jobs."},
    {"code": "job.delete", "module": "job", "action": "delete", "description": "Delete jobs."},
    {"code": "site_setting.read", "module": "site_setting", "action": "read", "description": "View site settings."},
    {"code": "site_setting.create", "module": "site_setting", "action": "create", "description": "Create site settings."},
    {"code": "site_setting.update", "module": "site_setting", "action": "update", "description": "Update site settings."},
    {"code": "site_setting.delete", "module": "site_setting", "action": "delete", "description": "Delete site settings."},
    {"code": "consultation.read", "module": "consultation", "action": "read", "description": "View consultations."},
    {"code": "consultation.update", "module": "consultation", "action": "update", "description": "Update consultation state."},
    {"code": "customer.read", "module": "customer", "action": "read", "description": "View customer records."},
    {"code": "customer.create", "module": "customer", "action": "create", "description": "Create customer records."},
    {"code": "customer.update", "module": "customer", "action": "update", "description": "Update customer records."},
    {"code": "customer.merge", "module": "customer", "action": "merge", "description": "Merge duplicate customers."},
    {"code": "service_request.read", "module": "service_request", "action": "read", "description": "View service requests."},
    {"code": "service_request.create", "module": "service_request", "action": "create", "description": "Create service requests."},
    {"code": "service_request.update", "module": "service_request", "action": "update", "description": "Update service requests."},
    {"code": "service_request.assign", "module": "service_request", "action": "assign", "description": "Manage service request assignments."},
    {"code": "service_request.status_update", "module": "service_request", "action": "status_update", "description": "Update service request status."},
    {"code": "service_request.mark_read", "module": "service_request", "action": "mark_read", "description": "Mark service request inbox items as read."},
    {"code": "service_request.bulk_update", "module": "service_request", "action": "bulk_update", "description": "Apply bulk updates across service requests."},
    {"code": "service_request.thread.read", "module": "service_request", "action": "thread.read", "description": "View service request threads."},
    {"code": "service_request.message.create", "module": "service_request", "action": "message.create", "description": "Create service request messages."},
    {"code": "service_request.note.create", "module": "service_request", "action": "note.create", "description": "Create service request notes."},
    {"code": "service_request.document.create", "module": "service_request", "action": "document.create", "description": "Upload service request documents."},
    {"code": "service_request.document.read", "module": "service_request", "action": "document.read", "description": "Read service request documents."},
    {"code": "review_queue.read", "module": "review_queue", "action": "read", "description": "View the unified content review queue."},
    {"code": "notification.read", "module": "notification", "action": "read", "description": "View in-app notifications."},
    {"code": "notification.update", "module": "notification", "action": "update", "description": "Mark notifications as read."},
    {"code": "notification.preference.read", "module": "notification", "action": "preference.read", "description": "View notification preferences."},
    {"code": "notification.preference.update", "module": "notification", "action": "preference.update", "description": "Manage notification preferences."},
    {"code": "report.read", "module": "report", "action": "read", "description": "View operational reports in admin."},
    {"code": "privacy_request.read", "module": "privacy_request", "action": "read", "description": "View privacy requests."},
    {"code": "privacy_request.manage", "module": "privacy_request", "action": "manage", "description": "Create and update privacy requests."},
    {"code": "user.read", "module": "user", "action": "read", "description": "View admin users."},
    {"code": "user.manage", "module": "user", "action": "manage", "description": "Manage admin users."},
    {"code": "role.read", "module": "role", "action": "read", "description": "View roles."},
    {"code": "role.manage", "module": "role", "action": "manage", "description": "Manage role-permission mappings."},
    {"code": "audit_log.read", "module": "audit_log", "action": "read", "description": "View audit logs."},
]

ROLE_PERMISSION_MAP = {
    "superuser": {item["code"] for item in PERMISSION_DEFINITIONS},
    "administrator": {
        item["code"]
        for item in PERMISSION_DEFINITIONS
        if item["code"] != "role.manage"
    },
    "editor": {
        "dashboard.read",
        "page.read",
        "page.create",
        "page.edit_own_draft",
        "page.submit_review",
        "blog_post.read",
        "blog_post.create",
        "blog_post.edit_own_draft",
        "blog_post.submit_review",
        "blog_category.read",
        "blog_author.read",
        "testimonial.read",
        "testimonial.create",
        "testimonial.edit_own_draft",
        "testimonial.submit_review",
        "media.read",
        "media.create",
        "media.update",
        "navigation.read",
        "pricing.read",
        "job.read",
        "customer.read",
        "service_request.read",
        "service_request.mark_read",
        "service_request.thread.read",
        "service_request.document.read",
        "review_queue.read",
        "notification.read",
        "notification.update",
        "notification.preference.read",
        "notification.preference.update",
        "report.read",
    },
    "reviewer": {
        "dashboard.read",
        "page.read",
        "page.approve",
        "page.reject",
        "blog_post.read",
        "blog_post.approve",
        "blog_post.reject",
        "blog_category.read",
        "blog_author.read",
        "testimonial.read",
        "testimonial.approve",
        "testimonial.reject",
        "media.read",
        "media.create",
        "media.update",
        "navigation.read",
        "pricing.read",
        "job.read",
        "customer.read",
        "service_request.read",
        "service_request.mark_read",
        "service_request.thread.read",
        "service_request.document.read",
        "review_queue.read",
        "notification.read",
        "notification.update",
        "notification.preference.read",
        "notification.preference.update",
        "report.read",
    },
    "viewer": {
        "dashboard.read",
        "page.read",
        "blog_post.read",
        "blog_category.read",
        "blog_author.read",
        "testimonial.read",
        "media.read",
        "navigation.read",
        "pricing.read",
        "job.read",
        "customer.read",
        "service_request.read",
        "service_request.mark_read",
        "service_request.thread.read",
        "service_request.document.read",
        "notification.read",
        "notification.update",
        "notification.preference.read",
        "notification.preference.update",
        "report.read",
    },
}


def get_all_permission_codes() -> list[str]:
    return [item["code"] for item in PERMISSION_DEFINITIONS]


def get_role_permission_codes(role_code: str) -> set[str]:
    return set(ROLE_PERMISSION_MAP.get(role_code, set()))


def sort_role_codes(role_codes: Iterable[str]) -> list[str]:
    return sorted(
        {role_code for role_code in role_codes if role_code},
        key=lambda role_code: (ROLE_PRIORITY.get(role_code, 999), role_code),
    )


def resolve_primary_role(role_codes: Iterable[str]) -> str | None:
    sorted_roles = sort_role_codes(role_codes)
    return sorted_roles[0] if sorted_roles else None
